#!/bin/bash                                                                                                                                           
mysqldump --add-drop-table -u root -p mugo > mugo.dump
svn commit -m "sql dump updated" ../mugo.dump
